### ISSUE TITLE
URL character encoding in source paths

### ISSUE THREAD

**Issue by msimkunas** [adrenth/redirect#20]
I've noticed that redirects won't work if you set the source path to a string containing non-English characters, such as ų or ū among others.

For instance, the source path `/rūkas` returns a 404. The reason for this is line 71 in Plugin.php: https://github.com/adrenth/redirect/blob/master/Plugin.php#L71

In this particular example, `Request::getRequestUri()` returns a URL-encoded string `/r%C5%ABkas` which, obviously, doesn't match the source path and returns a 404 error.

Specifying `/r%C5%ABkas` as the source path solves the problem (as a result, both `/rūkas` and `/r%C5%ABkas` redirect to the desired URL).

Should we specify source paths as URL-encoded strings (= intended behavior?) or is this actually a bug?

**Comment by adrenth** [comment]
Hi Mantas,

Thanks for noticing, a very interesting thing here. I haven't really thought about implementing non-English characters since OctoberCMS doesn't even allow these URL's entered in CMS Page URL. Frankly that's because I personally never use non-English characters :-)

This regex is used for URL validation when creating a CMS page `regex:/^\/[a-z0-9\/\:_\-\*\[\]\+\?\|\.\^\\\$]*$/i`.

![image](https://cloud.githubusercontent.com/assets/5699988/17068872/c17db976-5053-11e6-98cc-28f2a810f9fa.png)

But I assume other plugins allow using non-English characters in the URL and we should respect that. I rely on the output of `Request::getRequestUri()` and that method returns always an encoded URL string.

So, what about always storing the URL-encoded version in the database? So that when you enter `/rūkas` as a source path (or target path) the database value will always be `/r%C5%ABkas`.

At this moment I'm not sure if that change breaks other things, but seems a good "fix". Let me know what you think about it.

**Comment by adrenth** [comment]
I provided a fix for this issue in release 2.0.5. Can you also test this for me? That would be awesome. Let me know if you have any issues regarding this subject.

**Comment by msimkunas** [comment]
This is excellent. Thank you for such a quick reply!

I've tested the updated version of the plugin and it seems to work. Entering `/rūkas` as a source path creates a redirection rule where both `/rūkas` and `/r%C5%ABkas` (not that it shouldn't) redirect successfully to the destination URL.

I'll let you know if any further issues regarding this crop up. Thanks once again!
