### ISSUE TITLE
redirect doesn't work with october installed in a subdirectory

### ISSUE THREAD

**Issue by DennaGherlyn** [adrenth/redirect#21]
Hi,

it seems that redirect doesn't know how to handle paths if october is installed in a subdirectory. E.g. `http://example.com/october/`

The given path must be `/october/redirectedlink` instead of `/redirectedlink` to work.

**Comment by adrenth** [comment]
Ok, I get that. And that is an easy fix for the source path. 

Instead of using the `Request::getRequestUri()` method, we need to strip the base path from it: `$requestUri = str_replace(Request::getBasePath(), '', Request::getRequestUri());` (see bootFrontend() method in Plugin.php).

But the target path is a whole different story. The target path (as of now) can be anything, even a full external URL like `http://foobar.com`.

For example, if you want to do something like this:
http://example.com/october/old-blog
http://example.com/blog

That should also be possible.

So, to let's make it sense, I need to come up with a solution that can handle internal redirects and external redirects. And the only way to know that is that the user must specify if the target is an internal or external location.

Maybe you have some ideas? Please let me know.

**Comment by DennaGherlyn** [comment]
What about the classical definition?

- Paths beginning with the protocoll e.g. `http://` are handled as external link (as it is now). -> `http://foobar.com/externallink`
- Paths beginning with a `/`are absolute. E.g. `/absolutelink` -> `http://example.com/absolutelink` (no change here either)
- Paths not beginning with a `/` are relative. E.g. `relativelink` -> `http://example.com/october/relativelink`

**Comment by adrenth** [comment]
I agree with you. Thank you for writing it down. I'll implement it in the next release.

**Comment by adrenth** [comment]
Released version 2.0.6 which fixes this issue. It would be awesome if you'd test if this release fixes your issue.

And if you like this plugin, please rate it on octobercms.com ;-)

**Comment by DennaGherlyn** [comment]
Works great so far.
