### ISSUE TITLE
Install fails with PostgreSQL

### ISSUE THREAD

**Issue by CSNWEB** [adrenth/redirect#25]
When installing the plugin with postgres as database, it fails with the message: Unknown database type json requested. Which is weird as postgres supports json, I figured that the problem arises when the migrations try to change the redirects table. Not sure if this is a Problem with the underlying Doctrine dbal package.

**Comment by adrenth** [comment]
Thanks for creating this issue and providing a solution. The plugin does not officially support Postgres since I've never tested it on this database platform.

If it does not break on MySQL or SQLite platform it will be added in the next release of the plugin.

Please feel free to leave a review or any feedback on octobercms.com if you like this plugin. Thanks!

**Comment by adrenth** [comment]
I have merged your PR, could you test it with a fresh install for me? If it works correctly I can mark the plugin as Postgres compatible.
