### ISSUE TITLE
Efficiency 

### ISSUE THREAD

**Issue by poniatowski** [adrenth/redirect#40]
Hi Adrenth,

I've just installed your plugin for redirects. It's looks really good. Although, I've spotted some potential issues.  I'll try to explain some of my considerations below:

(1) In general I can't understand why you've created 3 columns (to_url, cms_page, static_page) with redirect to URL instead of one column? I think that approach cause a lots of problems. You can use one column and use column with target_type to indicate which type of page is it.

(2) E.g. ` $redirects = Redirect::all();` this bit is really make me sad.  Imagine situation where you have 9999 redirects in your database. With your plugin you gonna select all 9999 redirects at once in order to make just one redirect. That's not really efficient way. You should select just one redirect from you database, if that's possible :dancing_women: 

(3) Information like 'hits', 'last used', 'created at', 'updated at' can only slow down the website and I'm not sure if anyone will use it.

(4) Instead of 'match_type' column you can just check if 'requirements' column is empty or not. You don't need extra columns which slow down your website. Especialy in Google Analytics.

(5) If you don't like create another tables with list and foreign keys, better idea will be to use 'enum' instaed of 'char'.

Regards

**Comment by adrenth** [comment]
0) First, to make things clear is that this plugin doesn't use any database query for matching. And thus are all comments on database performance irrelevant. All redirect rules will be exported to a text-based file (in a specific format) which is used for redirect matching. So no database is hit on your site at all.

1) I chose for this database structure because it fits the Form model. I don't see why it causes a lot of problems. Why should this cause any troubles. The storage of these column values is perfectly handled in the Model.

2) 9999 redirects is totally not an issue for a database running on MySQL. See 0).

3) Fields such like `updated_at`, `created_at` are fields that are used by the Eloquent subsystem. Hit count (`hits`) and when a redirect is last touched (`last_used`) is very important for the SEO specialist. I don't see why storing extra data in a database will slow down performance of a website. And see 0)

4) See 0)

5) I'd like to avoid the ENUM field type to be compatible with other database platforms such as Postgresql, Sqlite for example.

I very much like some feedback, of any kind, but please provide some constructive feedback with benchmarks and tests to make your point. I recommend you to try and test this plugin on your website and I'm always happy to see your PR's coming. Thanks!
