### ISSUE TITLE
Strange issue, all redirects get unpublished randomly.

### ISSUE THREAD

**Issue by daniel-farina** [adrenth/redirect#7]
The latest updates look amazing, what a  good job. However I found a major bug, all the published redirects go unpublished randomly. For example if I delete one redirect, all the redirect get unpublished. 

This is quite serious if you have a lot of redirects. Is anyone else having the same issue? 

Thank you!

**Comment by daniel-farina** [comment]
I commented out line 84 & 85 

            //$redirect->setAttribute('hits', $redirect->getAttribute('hits') + 1);
           // $redirect->save();

This is a temporary fix. It will stop the hits counter, it seems every time the hits get updated it changes the published .

**Comment by daniel-farina** [comment]
modelsredirect.php

Line 99:

This is what is causing the problem, when something is dirty it will set it to false, Im commenting this out for now. 

$this->setAttribute('is_published', false);

on

    public function beforeSave()
    {
        if ($this->isDirty()) {
            //$this->setAttribute('is_published', false);
        }
    }

**Comment by adrenth** [comment]
Hi Dan,

Thank you for noticing. What you discovered is an unfinished piece of logic. 

Let me explain:

The reason that records are marked unpublished is because of the state of all rules haves changed. So they need to be published again. Also when you change te order of the rules, they need to be published again. I came up with a solution that when the model has changed it will be flagged as unpublished.

I forgot the fact that when the hitcounter was increased the same logic was executed. I need to fix fhat. 

I chose for the "publish" method because of performance reasons. Publishing means that al enabled rules will be exported in a .csv file somewhere in your storage folder of your project. The RedirectManager will parse this information much faster than querying that information from a database. So the URL matching does uses data directly from the database, but from memory.  

I'll fix this issue tomorrow along with some other issues. No patching needed, this one will be fixed very soon 😀

Please let other users know what your experiences are by leaving a review at octobercms.com

**Comment by adrenth** [comment]
Fixed in 1.0.6.
